/**
 * 雑談トーキング用のお題データ。
 *
 * 【お題を増やしたい/編集したいとき】
 * このファイルだけを編集すればよい。コンポーネント側のコードは
 * 変更不要（TOPIC_CATEGORIES の構造に従ってさえいれば自動的に反映される）。
 *
 * 新しいカテゴリを追加する場合は、id・labelKey（多言語キー）・icon・topics配列
 * を持つオブジェクトを TOPIC_CATEGORIES の配列に追加する。
 * labelKey は _i18n/translations.ts 側にも対応するキーを追加すること。
 *
 * 各カテゴリは50問で統一している。
 */

export interface TopicCategory {
  /** カテゴリの一意なID（URLや内部判定に使用、英数字推奨） */
  id: string;
  /** 表示名の翻訳キー（_i18n/translations.ts の 'topic.category.xxx' 形式） */
  labelKey: string;
  /** カテゴリを表す絵文字アイコン */
  icon: string;
  /** お題本文の配列。日本語/英語をそれぞれ持つ */
  topics: { ja: string; en: string }[];
}

export const TOPIC_CATEGORIES: TopicCategory[] = [
  {
    id: 'recent',
    labelKey: 'topic.category.recent',
    icon: '🗞️',
    topics: [
      { ja: '最近あった嬉しかったこと', en: 'Something good that happened to you recently' },
      { ja: '最近ハマっていること', en: 'Something you have been into lately' },
      { ja: '今週やったことの中で一番印象的だったこと', en: 'The most memorable thing you did this week' },
      { ja: '最近買ったもので一番気に入っているもの', en: 'Your favorite recent purchase' },
      { ja: '最近笑ったエピソード', en: 'Something that recently made you laugh' },
      { ja: '今年に入ってから始めたこと', en: 'Something you started doing this year' },
      { ja: '最近見た夢の話', en: 'A dream you had recently' },
      { ja: '最近行った場所でよかったところ', en: 'A nice place you visited recently' },
      { ja: '最近知って驚いた雑学やニュース', en: 'A trivia or news story that recently surprised you' },
      { ja: '今月中に達成したい小さな目標', en: 'A small goal you want to achieve this month' },
      { ja: '最近スマホで一番よく使っているアプリ', en: 'The smartphone app you have been using the most lately' },
      { ja: '最近買ってQOL（生活の質）が上がったもの', en: 'Something you bought recently that improved your life' },
      { ja: '最近お気に入りのライフハック', en: 'A life hack you have been loving recently' },
      { ja: '最近一番時間を使っていること', en: 'Something you have been spending the most time on lately' },
      { ja: '今週のちょっとした幸せ', en: 'A small happy moment from this week' },
      { ja: '最近もらって嬉しかったプレゼントや言葉', en: 'A gift or words that made you happy recently' },
      { ja: '最近行ってよかったお店', en: 'A shop or place you were glad you visited recently' },
      { ja: '今月、自分へのご褒美に買ったもの', en: 'Something you bought as a reward for yourself this month' },
      { ja: '最近やめた習慣', en: 'A habit you recently stopped' },
      { ja: '最近始めた新しい習慣', en: 'A new habit you recently started' },
      { ja: '今週一番びっくりしたこと', en: 'The most surprising thing this week' },
      { ja: '最近よく考えていること', en: 'Something you have been thinking about a lot lately' },
      { ja: '最近観て面白かった動画や配信', en: 'An interesting video or stream you watched recently' },
      { ja: '最近会えて嬉しかった人', en: 'Someone you were happy to see recently' },
      { ja: '今月読んだ・読んでいる本', en: 'A book you read or are reading this month' },
      { ja: '最近の自分のモチベーションの源', en: 'Your source of motivation lately' },
      { ja: '今年すでにやったことで一番良かったこと', en: 'The best thing you have done this year so far' },
      { ja: '最近お気に入りの音楽', en: 'Music you have been enjoying lately' },
      { ja: '最近ハマっている食べ物や飲み物', en: 'A food or drink you have been into lately' },
      { ja: '今週、誰かに感謝したこと', en: 'Something you were thankful to someone for this week' },
      { ja: '最近の自分の小さな成長', en: 'A small way you have grown recently' },
      { ja: '今月の目標', en: 'Your goal for this month' },
      { ja: '最近ちょっと頑張ったこと', en: 'Something you put a little extra effort into recently' },
      { ja: '最近気になっているニュースや話題', en: 'A news story or topic you are curious about lately' },
      { ja: '今年新しく出会った人との思い出', en: 'A memory with someone you met this year' },
      { ja: '最近お気に入りの場所', en: 'A place you have been enjoying lately' },
      { ja: '最近見た中で一番面白かった広告やCM', en: 'The funniest ad or commercial you have seen recently' },
      { ja: '最近やった中で一番リフレッシュできたこと', en: 'The most refreshing thing you did recently' },
      { ja: '今週の自分を一言で表すと？', en: 'Describe your week in one word' },
      { ja: '最近どんな失敗をした？', en: 'What mistake did you make recently?' },
      { ja: '最近知って得した情報', en: 'Useful information you learned recently' },
      { ja: '今月新しく試したこと', en: 'Something new you tried this month' },
      { ja: '最近見て泣いた・感動したもの', en: 'Something that recently made you cry or moved you' },
      { ja: '最近の自分にとっての一番のニュース', en: 'The biggest news in your life recently' },
      { ja: '今年すでに行った場所で一番良かったところ', en: 'The best place you have visited this year so far' },
      { ja: '最近気になっているお店やブランド', en: 'A shop or brand you are curious about lately' },
      { ja: '最近、誰かにおすすめされて良かったもの', en: 'Something someone recommended to you recently that turned out great' },
      { ja: '最近ちょっと贅沢したこと', en: 'A small luxury you treated yourself to recently' },
      { ja: '最近の悩み事', en: 'A problem or concern you have recently' },
    ],
  },
  {
    id: 'hobby',
    labelKey: 'topic.category.hobby',
    icon: '🎮',
    topics: [
      { ja: '今一番好きなゲーム・作品', en: 'Your current favorite game or show' },
      { ja: '休日の過ごし方', en: 'How you spend your days off' },
      { ja: '一度はやってみたい趣味', en: 'A hobby you would like to try someday' },
      { ja: '好きな音楽のジャンル・アーティスト', en: 'Your favorite music genre or artist' },
      { ja: 'コレクションしているもの', en: 'Something you collect' },
      { ja: '推しのキャラクター・人物', en: 'Someone or something you are a big fan of' },
      { ja: '時間を忘れて没頭できること', en: 'Something you can lose track of time doing' },
      { ja: '好きな映画・ドラマのジャンル', en: 'Your favorite movie or drama genre' },
      { ja: '人にはあまり理解されないマイナーな趣味', en: 'A niche hobby that others might not easily understand' },
      { ja: '一生に一度は現地で生観戦・鑑賞してみたいもの', en: 'Something you want to see live in person at least once' },
      { ja: '「これなら何時間でも語れる」というテーマ', en: 'A topic you could talk about for hours' },
      { ja: '作業中によく聴いている音楽やラジオ', en: 'The music or radio you usually listen to while working' },
      { ja: 'インドア派？それともアウトドア派？', en: 'Are you an indoor person or an outdoor person?' },
      { ja: '昔好きだったけど今はやっていない趣味', en: 'A hobby you used to love but no longer do' },
      { ja: '人に勧めたい漫画・アニメ・小説', en: 'A manga, anime, or novel you would recommend to others' },
      { ja: '友達と一緒にやって楽しいゲーム', en: 'A fun game to play with friends' },
      { ja: '一番お金をかけている趣味', en: 'The hobby you spend the most money on' },
      { ja: '推し活でやっていること', en: 'Something you do to support someone or something you are a fan of' },
      { ja: '好きなジャンルの映画やアニメの「最初の1作」', en: 'The first movie or anime that got you into that genre' },
      { ja: '好きな漫画家・作家・クリエイター', en: 'Your favorite manga artist, author, or creator' },
      { ja: '趣味に使っている年間の予算', en: 'How much you spend on your hobby per year' },
      { ja: '一緒に趣味を楽しめる友達はいる？', en: 'Do you have friends who share your hobby?' },
      { ja: '昔ハマっていたブームやトレンド', en: 'A trend or fad you were really into in the past' },
      { ja: '好きなボードゲームやカードゲーム', en: 'Your favorite board game or card game' },
      { ja: 'カラオケで必ず歌う曲', en: 'A song you always sing at karaoke' },
      { ja: '一番長く続けている趣味', en: 'The hobby you have continued the longest' },
      { ja: '趣味で一番上達したと感じること', en: 'Something you feel you have gotten really good at through your hobby' },
      { ja: '好きなスポーツ観戦（する/見る）', en: 'Your favorite sport to play or watch' },
      { ja: '始めてみたい楽器', en: 'An instrument you would like to start playing' },
      { ja: '好きな写真や動画の撮り方のこだわり', en: 'Your style or preference when taking photos or videos' },
      { ja: 'イベントやライブの思い出', en: 'A memory of an event or live performance' },
      { ja: '一番熱中して時間を忘れたゲーム', en: 'A game you got so absorbed in you forgot the time' },
      { ja: '好きなキャラクターグッズやコレクション', en: 'Character merchandise or a collection you love' },
      { ja: '子供の頃好きだった遊び', en: 'A game you loved playing as a kid' },
      { ja: '一人でできる趣味と誰かと一緒にやる趣味、どっちが好き？', en: 'Do you prefer hobbies you do alone or with others?' },
      { ja: '趣味にハマったきっかけ', en: 'What got you into your hobby' },
      { ja: '最近YouTubeやSNSでよく見る動画のジャンル', en: 'The genre of videos you often watch on YouTube or SNS recently' },
      { ja: '休日に必ずやるルーティン', en: 'Something you always do on your day off' },
      { ja: '昔から変わらず好きなもの', en: 'Something you have loved consistently since you were young' },
      { ja: '趣味にどれくらいの時間をかけている？', en: 'How much time do you spend on your hobby?' },
      { ja: '趣味を通じて得た友達やつながり', en: 'Friends or connections you made through your hobby' },
      { ja: '一番好きな漫画・アニメのキャラクター', en: 'Your favorite manga or anime character' },
    ],
  },
  {
    id: 'food',
    labelKey: 'topic.category.food',
    icon: '🍜',
    topics: [
      { ja: '好きな食べ物ベスト3', en: 'Your top 3 favorite foods' },
      { ja: '最近食べて美味しかったもの', en: 'Something delicious you ate recently' },
      { ja: '苦手な食べ物', en: 'A food you do not like' },
      { ja: '自分で作れる得意料理', en: 'A dish you are good at cooking' },
      { ja: '一度は行ってみたいお店・レストラン', en: 'A restaurant you would like to visit someday' },
      { ja: 'コンビニで必ず買うもの', en: 'Something you always buy at a convenience store' },
      { ja: '好きなお菓子・スイーツ', en: 'Your favorite snack or dessert' },
      { ja: '最後の晩餐に食べたいもの', en: 'What you would want for your last meal' },
      { ja: 'おすすめのご当地グルメや特産品', en: 'Your favorite regional food or local specialty' },
      { ja: 'ラーメンは「何味」が一番好き？', en: 'What is your favorite ramen flavor?' },
      { ja: '目玉焼きには何をかける？', en: 'What do you put on your fried eggs?' },
      { ja: '最高の「ご飯のお供」といえば？', en: 'What is the ultimate side dish to eat with white rice?' },
      { ja: '甘いものと辛いもの、どっちが好き？', en: 'Do you prefer sweet food or spicy food?' },
      { ja: '家でよく作る簡単な料理', en: 'A simple dish you often make at home' },
      { ja: '初めて食べて衝撃を受けた食べ物', en: 'A food that shocked you the first time you tried it' },
      { ja: 'お酒は好き？好きなお酒の種類は？', en: 'Do you like alcohol? What is your favorite type?' },
      { ja: '朝ごはんは食べる派？それとも食べない派？', en: 'Do you eat breakfast every day or skip it?' },
      { ja: 'パンとご飯、どっちが好き？', en: 'Do you prefer bread or rice?' },
      { ja: 'インスタント食品で一番好きなもの', en: 'Your favorite instant food' },
      { ja: '好きな鍋の種類', en: 'Your favorite type of hot pot' },
      { ja: '外食と自炊、どっちが多い？', en: 'Do you eat out more or cook at home more?' },
      { ja: '好きな調味料やソース', en: 'Your favorite seasoning or sauce' },
      { ja: '一度は食べてみたい高級料理', en: 'A fancy dish you would like to try someday' },
      { ja: '好きなお寿司のネタ', en: 'Your favorite sushi topping' },
      { ja: 'カレーは何が好き？（辛さ・種類など）', en: 'What kind of curry do you like? (Spice level, type, etc.)' },
      { ja: '好きな飲み物（お酒以外）', en: 'Your favorite non-alcoholic drink' },
      { ja: '好きなパンの種類', en: 'Your favorite type of bread' },
      { ja: '一番好きなファストフード', en: 'Your favorite fast food' },
      { ja: '食べ放題で必ず頼むもの', en: 'Something you always order at an all-you-can-eat restaurant' },
      { ja: '好きな果物ベスト3', en: 'Your top 3 favorite fruits' },
      { ja: '手土産に選ぶならどんなお菓子？', en: 'What kind of snack would you choose as a gift?' },
      { ja: '好きな麺類', en: 'Your favorite type of noodles' },
      { ja: 'コーヒーと紅茶、どっちが好き？', en: 'Do you prefer coffee or tea?' },
      { ja: '好きな揚げ物', en: 'Your favorite fried food' },
      { ja: '味の好みは濃い味派？薄味派？', en: 'Do you prefer strong flavors or light flavors?' },
      { ja: 'お弁当に入っていたら嬉しいもの', en: 'Something you would be happy to find in your bento' },
      { ja: '食わず嫌いはある？', en: 'Do you have any food you refuse to eat even without trying it?' },
      { ja: '一番好きな卵料理', en: 'Your favorite egg dish' },
      { ja: 'お祝いの日に食べたいもの', en: 'What you want to eat on a celebration day' },
      { ja: 'お酒に合うつまみで一番好きなもの', en: 'Your favorite snack to go with alcohol' },
      { ja: 'スイーツでチョコ系とフルーツ系どっちが好き？', en: 'Do you prefer chocolate-based or fruit-based desserts?' },
      { ja: '好きなアイスの味', en: 'Your favorite ice cream flavor' },
      { ja: '自炊で一番得意な料理ジャンル', en: 'The genre of cooking you are best at' },
      { ja: '旅行先で必ず食べるご当地グルメ', en: 'A local food you always eat when traveling' },
      { ja: 'コンビニスイーツで一番好きなもの', en: 'Your favorite convenience store dessert' },
      { ja: '何パスタが好き？', en: 'What is your favorite type of pasta?' },
      { ja: '朝食はご飯派？パン派？', en: 'Do you prefer rice or bread for breakfast?' },
    ],
  },
  {
    id: 'travel',
    labelKey: 'topic.category.travel',
    icon: '✈️',
    topics: [
      { ja: '今まで行った中で一番良かった場所', en: 'The best place you have ever traveled to' },
      { ja: '次に行きたい旅行先', en: 'Where you want to travel next' },
      { ja: '旅行で絶対に持っていくもの', en: 'Something you always bring on a trip' },
      { ja: '海外と国内どっちが好き？', en: 'Do you prefer traveling abroad or domestically?' },
      { ja: '旅行先での失敗エピソード', en: 'A travel mishap you experienced' },
      { ja: '住んでみたい国・都市', en: 'A country or city you would like to live in' },
      { ja: '弾丸旅行（日帰りや一泊）で行ってみたい場所', en: 'A place you would like to go for a quick weekend trip' },
      { ja: '旅先での移動時間は何をして過ごす？', en: 'How do you pass the time while traveling to your destination?' },
      { ja: '旅行の計画はガチガチに立てる派？行き当たりばったり派？', en: 'Do you plan trips thoroughly or just wing it?' },
      { ja: 'まだ行ったことがないけれど、いつか絶対に行きたい都道府県', en: 'A prefecture you have never been to but definitely want to visit' },
      { ja: 'おすすめの、または行ってみたい「温泉地」', en: 'A hot spring resort you recommend or want to visit' },
      { ja: '旅行に行くなら一人旅とグループ旅行どっちが好き？', en: 'Do you prefer traveling alone or with a group?' },
      { ja: '旅先で必ず買うお土産', en: 'A souvenir you always buy when traveling' },
      { ja: '飛行機・新幹線・車、移動手段で一番好きなもの', en: 'Your favorite way to travel: plane, bullet train, or car?' },
      { ja: '旅行先で必ずすること', en: 'Something you always do when traveling' },
      { ja: '国内旅行で一番おすすめのスポット', en: 'Your top recommended spot for domestic travel' },
      { ja: '海外旅行で行ってみたい国', en: 'A country abroad you would like to visit' },
      { ja: '旅行の予算はどれくらいかける？', en: 'How much budget do you set for travel?' },
      { ja: '旅行に行くなら山派？海派？', en: 'Do you prefer the mountains or the sea when traveling?' },
      { ja: '旅先のホテルや宿で重視すること', en: 'What you value most in a hotel or accommodation' },
      { ja: '旅行のしおりや計画は作る派？', en: 'Do you make a detailed itinerary for trips?' },
      { ja: '旅先で写真を撮るときのこだわり', en: 'Your preference when taking photos while traveling' },
      { ja: '旅行の思い出で一番笑った出来事', en: 'The funniest memory from a trip' },
      { ja: '長期休暇があったら行きたい場所', en: 'Where you would go if you had a long vacation' },
      { ja: '飛行機の席は窓側？通路側？', en: 'Do you prefer window or aisle seats on a plane?' },
      { ja: '旅行の準備で一番楽しい工程', en: 'The most fun part of preparing for a trip' },
      { ja: 'もし友達を旅行に連れて行くならどこをおすすめする？', en: 'Where would you recommend if you were taking a friend on a trip?' },
      { ja: '旅先で一番感動した景色', en: 'The most moving scenery you have seen while traveling' },
      { ja: '車・バイク・自転車での旅は好き？', en: 'Do you enjoy traveling by car, motorcycle, or bicycle?' },
      { ja: '旅行先で困ったハプニング', en: 'A troublesome incident that happened during a trip' },
      { ja: 'キャンプや車中泊に興味はある？', en: 'Are you interested in camping or sleeping in a car?' },
      { ja: '日帰り旅行で行きたい場所', en: 'A place you would like to go for a day trip' },
      { ja: '旅行に誘うなら誰と行きたい？', en: 'Who would you invite on a trip?' },
      { ja: '夜景がきれいな場所でおすすめのスポット', en: 'A recommended spot with a beautiful night view' },
      { ja: '旅先での移動中に聴く音楽やラジオ', en: 'Music or radio you listen to while traveling' },
      { ja: '旅行中の食事は現地のものを楽しむ派？', en: 'Do you enjoy trying local food while traveling?' },
      { ja: '今まで行った旅行先で一番驚いたこと', en: 'The most surprising thing you experienced on a trip' },
      { ja: '旅行カバンの中で必ず入れるもの', en: 'Something you always pack in your travel bag' },
      { ja: '観光地巡りとのんびり過ごす旅、どっちが好き？', en: 'Do you prefer sightseeing trips or relaxing trips?' },
      { ja: '旅行で一番記憶に残っている宿', en: 'The accommodation you remember most from a trip' },
      { ja: '島旅・離島に行ってみたい？', en: 'Would you like to visit an island or remote island?' },
      { ja: '旅行中にやってよかった失敗談', en: 'A travel mishap that turned out to be a good experience' },
      { ja: '温泉やスパでのお気に入りの過ごし方', en: 'Your favorite way to enjoy a hot spring or spa' },
      { ja: '今までで一番移動時間が長かった旅行', en: 'The trip with the longest travel time you have ever had' },
      { ja: '世界遺産で行ってみたい場所', en: 'A World Heritage site you would like to visit' },
      { ja: '旅先での出会いやエピソード', en: 'An encounter or episode from a trip' },
      { ja: '旅行は何日くらいが理想？', en: 'How many days do you think is ideal for a trip?' },
    ],
  },
  {
    id: 'work',
    labelKey: 'topic.category.work',
    icon: '💼',
    topics: [
      { ja: '今の仕事・学業で大変なこと', en: 'Something challenging about your work or studies right now' },
      { ja: '仕事や勉強のやる気を上げる方法', en: 'How you motivate yourself for work or study' },
      { ja: '将来やってみたいこと', en: 'Something you would like to do in the future' },
      { ja: '今の自分に一番必要なスキル', en: 'A skill you think you need most right now' },
      { ja: '尊敬する人・憧れの人', en: 'Someone you admire or respect' },
      { ja: '小さい頃の将来の夢', en: 'What you wanted to be when you were a kid' },
      { ja: '自分の「集中スイッチ」を入れるルーティン', en: 'Your routine for getting into the zone' },
      { ja: '今までで一番買ってよかったデスク周りのガジェット・文房具', en: 'The best desk gadget or stationery you have ever bought' },
      { ja: '理想的な「理想の1日のスケジュール」', en: 'Your ideal daily schedule' },
      { ja: '仕事や勉強で行き詰まったときの気晴らし方法', en: 'How you refresh yourself when you get stuck' },
      { ja: '朝型人間？それとも夜型人間？', en: 'Are you a morning person or a night person?' },
      { ja: '今までで一番大変だったアルバイトや仕事', en: 'The hardest part-time job or work you have ever had' },
      { ja: 'もし今の仕事を辞めるとしたら、次にやりたいこと', en: 'If you quit your current job, what would you want to do next?' },
      { ja: '仕事や勉強の効率を上げるために使っている道具やアプリ', en: 'A tool or app you use to be more productive at work or study' },
      { ja: '仕事や勉強の休憩時間に必ずすること', en: 'Something you always do during a break from work or study' },
      { ja: '在宅と出社、どっちが好き？', en: 'Do you prefer working from home or going to the office?' },
      { ja: '仕事や勉強で一番達成感を感じた瞬間', en: 'A moment you felt the most accomplished at work or study' },
      { ja: '新しい職場や環境に慣れるためにすること', en: 'Something you do to adjust to a new workplace or environment' },
      { ja: '仕事や勉強の合間の飲み物・お菓子', en: 'Your go-to drink or snack during work or study breaks' },
      { ja: '理想の働き方', en: 'Your ideal way of working' },
      { ja: '仕事や勉強でストレスを感じる原因', en: 'What causes you stress at work or study' },
      { ja: 'やる気が出ないときの対処法', en: 'How you deal with not feeling motivated' },
      { ja: '将来挑戦してみたい仕事や役職', en: 'A job or position you would like to challenge yourself with in the future' },
      { ja: '仕事・勉強で一番感謝した人', en: 'Someone you were most thankful to at work or study' },
      { ja: 'デスク周りで欠かせないアイテム', en: 'An essential item on your desk' },
      { ja: '仕事や勉強の効率が上がる時間帯', en: 'The time of day when you are most productive' },
      { ja: '今までで一番嬉しかった評価や成果', en: 'The most pleasing evaluation or achievement you have received' },
      { ja: '転職や進路を考えたことはある？', en: 'Have you ever considered changing jobs or career paths?' },
      { ja: '仕事・学業で身につけたい資格やスキル', en: 'A certification or skill you want to acquire for work or study' },
      { ja: '上司・先輩・先生から学んだ印象的な言葉', en: 'A memorable piece of advice from a boss, senior, or teacher' },
      { ja: '仕事や勉強の息抜きにやること', en: 'What you do to take a break from work or study' },
      { ja: '今の自分の強み', en: 'Your current strength' },
      { ja: 'これまでで一番大変だったプロジェクトや課題', en: 'The most challenging project or task you have had' },
      { ja: '会議やプレゼンで緊張しない方法', en: 'How you avoid being nervous during meetings or presentations' },
      { ja: '将来のキャリアプラン', en: 'Your future career plan' },
      { ja: '仕事や勉強仲間との理想的な関係', en: 'Your ideal relationship with coworkers or classmates' },
      { ja: '今欲しい仕事道具や勉強道具', en: 'A work or study tool you currently want' },
      { ja: '新しい知識を学ぶときに使う方法', en: 'A method you use when learning something new' },
      { ja: '今までで一番印象的だった面接やプレゼン', en: 'The most memorable interview or presentation you have had' },
      { ja: '仕事や勉強の目標を立てるときのこだわり', en: 'Your approach when setting goals for work or study' },
      { ja: '副業や個人の活動に興味はある？', en: 'Are you interested in side jobs or personal projects?' },
      { ja: 'チームで作業するのと一人で作業するの、どっちが好き？', en: 'Do you prefer working in a team or alone?' },
      { ja: '仕事や勉強の合間にリフレッシュする方法', en: 'How you refresh yourself between work or study sessions' },
      { ja: '今の仕事や学業で一番楽しいこと', en: 'The most enjoyable part of your current job or studies' },
      { ja: '昔の自分に伝えたい仕事・勉強のアドバイス', en: 'Advice about work or study you would give your past self' },
      { ja: '将来住みたい場所と仕事の関係', en: 'How your future job relates to where you want to live' },
      { ja: '仕事や勉強で意識している時間管理術', en: 'A time management technique you use for work or study' },
      { ja: '仕事や勉強で「これだけは譲れない」と思うこだわり', en: 'Something you absolutely will not compromise on at work or study' },
      { ja: '仕事や勉強で一番使っている時間管理ツール', en: 'The time management tool you use most for work or study' },
    ],
  },
  {
    id: 'fun',
    labelKey: 'topic.category.fun',
    icon: '🎉',
    topics: [
      { ja: 'もし1億円もらったら何をする？', en: 'What would you do if you got 100 million yen?' },
      { ja: '無人島に1つだけ持っていけるなら何を持っていく？', en: 'If you could bring only one thing to a desert island, what would it be?' },
      { ja: 'タイムリープできるならいつに行きたい？', en: 'If you could time travel, when would you go?' },
      { ja: '1日だけ別人になれるなら誰になりたい？', en: 'If you could be someone else for a day, who would you be?' },
      { ja: '超能力を1つ手に入れられるなら何が欲しい？', en: 'If you could have one superpower, what would it be?' },
      { ja: '自分を動物で例えると何？', en: 'If you were an animal, which one would you be?' },
      { ja: '明日から1週間、完全に自由な休みになったら何をする？', en: 'What would you do if you suddenly got a week of completely free time starting tomorrow?' },
      { ja: '過去の自分に1つだけアドバイスできるなら、いつの自分に何て言う？', en: 'If you could give one piece of advice to your past self, when and what would it be?' },
      { ja: '魔法が1つだけ使えるなら、どんな魔法がいい？', en: 'If you could use just one magic spell, what would it be?' },
      { ja: '宝くじで100万円当たったら、何に使う？', en: 'What would you do if you won 1 million yen in the lottery?' },
      { ja: '自分のトリセツがあるとしたら、絶対に書いてあることは？', en: 'If you had an instruction manual, what would be the most important rule in it?' },
      { ja: '世界中の言葉を1つだけ覚えられるなら何語を選ぶ？', en: 'If you could instantly learn one language, which would you choose?' },
      { ja: '生まれ変わるなら、違う時代と違う国、どちらに生まれたい？', en: 'If you were reborn, would you choose a different era or a different country?' },
      { ja: 'もし自分が漫画の主人公なら、どんな能力を持っていそう？', en: 'If you were the main character of a manga, what kind of power would you have?' },
      { ja: '1日だけ世界のルールを1つ変えられるとしたら、何を変える？', en: 'If you could change one rule of the world for a day, what would it be?' },
      { ja: '動物と話せるようになったら一番話したい動物は？', en: 'If you could talk to animals, which one would you talk to first?' },
      { ja: '異世界に転生するなら、どんな世界がいい？', en: 'If you were reincarnated in another world, what kind of world would you want?' },
      { ja: '1日だけ有名人になれるなら誰になりたい？', en: 'If you could be a celebrity for a day, who would you choose?' },
      { ja: 'タイムマシンに乗れるなら、過去と未来どっちに行きたい？', en: 'If you could use a time machine, would you go to the past or the future?' },
      { ja: '時間を止められる能力があったら何に使う？', en: 'If you could stop time, what would you use it for?' },
      { ja: 'どんな相手でも本当のことを答えてもらえるなら、誰に何を聞く？', en: 'If you could ask anyone one question and get a truthful answer, who and what would you ask?' },
      { ja: '世界中のどこにでも瞬間移動できるなら、今すぐどこに行く？', en: 'If you could teleport anywhere in the world right now, where would you go?' },
      { ja: '1日だけ歴史上の人物になれるなら誰になりたい？', en: 'If you could become a historical figure for a day, who would you choose?' },
      { ja: '明日地球がなくなるとしたら、今日何をする？', en: 'If the world were ending tomorrow, what would you do today?' },
      { ja: '夢を1つだけ確実に叶えられるなら何を選ぶ？', en: 'If you could guarantee one dream comes true, what would you choose?' },
      { ja: '透明になれる時間が1時間あったら何をする？', en: 'If you had one hour of invisibility, what would you do?' },
      { ja: '好きなだけ若返ることができるなら何歳に戻りたい？', en: 'If you could become any age younger, what age would you go back to?' },
      { ja: '人生で一つだけやり直せるとしたら、いつに戻る？', en: 'If you could redo just one moment in your life, what would you go back to?' },
      { ja: 'アニメキャラクターと友達になれるなら誰がいい？', en: 'If you could be friends with an anime character, who would you choose?' },
      { ja: 'ロボットに1つだけ仕事を完全に任せられるなら何を任せる？', en: 'If you could fully delegate one task to a robot, what would it be?' },
      { ja: '1日だけ別の年齢の自分になれるなら何歳になりたい？', en: 'If you could become a different age for a day, what age would you choose?' },
      { ja: '世界に1つだけ新しいルールを作れるなら、どんなルールにする？', en: 'If you could create one new rule for the world, what would it be?' },
      { ja: 'もし異能力バトルに巻き込まれたら、自分はどんな立ち位置になりそう？', en: 'If you were caught up in a battle of super powers, what role do you think you would play?' },
      { ja: '自分の人生の続きが書かれた本があったら、読む？', en: 'If there were a book that continued the story of your life, would you read it?' },
      { ja: '地球上のどこにでも家を建てられるなら、どこに建てる？', en: 'If you could build a house anywhere on Earth, where would you build it?' },
      { ja: '自分専用のテーマソングを作れるなら、どんな曲調にする？', en: 'If you could have your own theme song, what style of music would it be?' },
      { ja: '1日だけ猫または犬になれるなら、どっちになりたい？', en: 'If you could be a cat or a dog for a day, which would you choose?' },
      { ja: '人生をやり直せるなら、もう一度同じ人生を選ぶ？', en: 'If you could redo your life, would you choose the same life again?' },
      { ja: '1日だけ世界共通の祝日を作れるなら、何の日にする？', en: 'If you could create a world holiday for one day, what would it celebrate?' },
      { ja: '好きな食べ物だけで生きられるとしたら何を選ぶ？', en: 'If you could survive on only one food, what would you choose?' },
      { ja: '過去の選択を一つだけ変えられるとしたら、何を変える？', en: 'If you could change one choice from your past, what would it be?' },
      { ja: 'もし1日だけ透明人間になれるなら、どこへ行く？', en: 'If you could be invisible for a day, where would you go?' },
      { ja: '自分の人生を映画化するなら、誰に主演を頼む？', en: 'If your life were made into a movie, who would you want to play you?' },
      { ja: '明日から1ヶ月無人島生活、3つだけ持っていけるなら何を持っていく？', en: 'If you had to live on a desert island for a month, what three things would you bring?' },
      { ja: '宇宙旅行に行けるとしたら、どこへ行ってみたい？', en: 'If you could go on a space trip, where would you want to go?' },
      { ja: '人生で一番の「神回」だった出来事は？', en: 'What was the "best episode" of your life so far?' },
      { ja: 'もし自分のクローンが作れるなら、何を任せる？', en: 'If you could create a clone of yourself, what would you have it do?' },
      { ja: '架空の世界に住めるなら、魔法がある世界と科学が発達した世界どっちがいい？', en: 'If you could live in a fictional world, would you prefer a world with magic or advanced technology?' },
      { ja: 'もし自分が伝説の生物なら、何になりたい？', en: 'If you were a legendary creature, which one would you want to be?' },
      { ja: '世界中のすべての料理から1つだけ食べ続けられるなら何を選ぶ？', en: 'If you could eat only one dish from all the cuisines in the world for the rest of your life, what would it be?' },
      { ja: '自分専用の執事やメイドを雇えるなら、どんな人にお願いする？', en: 'If you could hire a personal butler or maid, what kind of person would you choose?' },
      { ja: '自分の人生を本にするなら、タイトルは何にする？', en: 'If you were to write a book about your life, what would the title be?' },
      { ja: 'もし1週間、寝なくても平気な体になったら何をする？', en: 'If you didn’t need to sleep for a week, what would you do?' },
      { ja: '自分の記憶を1つだけ消せるとしたら、何を消す？', en: 'If you could delete just one memory, what would it be?' },
      { ja: 'もし空が好きな色に変えられるとしたら、何色にする？', en: 'If you could change the color of the sky, what color would you choose?' },
      { ja: '一生に一度だけ、超一流の技術をマスターできるなら何を選ぶ？', en: 'If you could master one elite skill, what would you pick?' },
      { ja: 'もし自分が物語の悪役なら、どんな悪事をする？', en: 'If you were a villain in a story, what kind of villainy would you do?' },
      { ja: 'もし1日だけ、どんな動物とも入れ替われるなら何になる？', en: 'If you could swap bodies with any animal for a day, which one would it be?' },
      { ja: '自分の子供時代に、現代のテクノロジーを1つだけ持っていけるなら何を持っていく？', en: 'If you could take one modern piece of technology back to your childhood, what would it be?' },
      { ja: 'もし世界中の宝物を1つだけ手に入れられるなら、何にする？', en: 'If you could possess any one treasure in the world, what would it be?' },
      { ja: 'もし1日だけ、予知能力が使えるなら何に使う？', en: 'If you had the power of foresight for one day, how would you use it?' },
      { ja: 'どんなスポーツでもプロになれるなら、何の選手になる？', en: 'If you could be a professional in any sport, which would you choose?' },
      { ja: 'もし一生、天気が1種類しか選べないなら何にする？', en: 'If you had to choose one type of weather for the rest of your life, what would it be?' },
      { ja: '自分の名前を自由に変えられるとしたら、どんな名前にする？', en: 'If you could change your name, what would you change it to?' },
      { ja: 'もし、夢の中で見たい景色を自由に作れるなら？', en: 'If you could design the scenery of your dreams, what would it look like?' },
      { ja: '自分の人生のナレーションを、有名人にお願いできるとしたら誰？', en: 'If you could have a celebrity narrate your life, who would you choose?' },
      { ja: 'もし、人生で一度だけ大逆転のチャンスが来るとしたら何をする？', en: 'If you could have one moment in your life for a massive comeback, what would it be?' },
    ]
  },
  {
    id: 'lifestyle',
    labelKey: 'topic.category.lifestyle',
    icon: '🏠',
    topics: [
      { ja: '家の中で一番落ち着くお気に入りの場所', en: 'Your favorite, most relaxing spot in your house' },
      { ja: '睡眠の質を上げるためにこだわっていること', en: 'Something you do to improve your sleep quality' },
      { ja: '部屋のインテリアや模様替えのこだわり', en: 'Your preferences for room decor or rearranging furniture' },
      { ja: '好きな季節とその理由', en: 'Your favorite season and why' },
      { ja: 'やめたいけれど、ついやっちゃう悪い習慣', en: 'A bad habit you want to quit but keep doing' },
      { ja: 'おうち時間は何をして過ごすのが一番好き？', en: 'What is your favorite way to spend time at home?' },
      { ja: '普段の生活で「これだけは譲れない」というこだわり', en: 'A personal rule or preference you cannot compromise on in daily life' },
      { ja: 'おすすめの、またはお気に入りのリラックス方法', en: 'Your favorite way to relax' },
      { ja: '服やファッションを選ぶときの一番のこだわり', en: 'Your top priority when choosing clothes or fashion' },
      { ja: 'ペットを飼うなら何を飼いたい？（または今飼っているペットの自慢）', en: 'What kind of pet would you want to have? (Or brag about your current pet)' },
      { ja: '一人暮らしと実家暮らし、どちらが好き？', en: 'Do you prefer living alone or living with family?' },
      { ja: '休みの日の理想的な過ごし方', en: 'Your ideal way to spend a day off' },
      { ja: '掃除や整理整頓は得意？それとも苦手？', en: 'Are you good at cleaning and organizing, or not so much?' },
      { ja: '愛用している家電や生活グッズ', en: 'A home appliance or daily item you love using' },
      { ja: '朝起きてから必ずやるルーティン', en: 'A routine you always do right after waking up' },
      { ja: '夜寝る前のルーティン', en: 'Your routine before going to bed' },
      { ja: 'お風呂は長め派？短め派？', en: 'Do you take long baths or quick ones?' },
      { ja: '休日の理想の朝ごはん', en: 'Your ideal breakfast on a day off' },
      { ja: '一人の時間で一番好きな過ごし方', en: 'Your favorite way to spend time alone' },
      { ja: '生活の中で一番こだわっている時間帯', en: 'The time of day you care about the most in your daily life' },
      { ja: 'お気に入りのルームウェアやパジャマ', en: 'Your favorite room wear or pajamas' },
      { ja: '生活費の中で一番お金をかけているもの', en: 'What you spend the most money on in your daily life' },
      { ja: '好きな香りやアロマ', en: 'Your favorite scent or aroma' },
      { ja: '家でよく聴く音楽やラジオ', en: 'Music or radio you often listen to at home' },
      { ja: '普段の移動手段で好きなもの', en: 'Your favorite way to commute or get around' },
      { ja: '休日と平日でライフスタイルはどう違う？', en: 'How is your lifestyle different on weekdays versus weekends?' },
      { ja: '一日のうちで一番好きな時間帯', en: 'Your favorite time of day' },
      { ja: '買い物は計画派？衝動買い派？', en: 'Are you a planned shopper or an impulse buyer?' },
      { ja: 'お気に入りの文房具や日用品', en: 'Your favorite stationery or daily item' },
      { ja: '生活の中で一番のこだわりポイント', en: 'The thing you care about most in your daily life' },
      { ja: '最近の暮らしで変えたいこと', en: 'Something about your lifestyle you would like to change' },
      { ja: '理想の部屋の広さや住環境', en: 'Your ideal room size or living environment' },
      { ja: '一人暮らしを始めて気づいたこと（または実家暮らしの良さ）', en: 'Something you realized after living alone (or the benefits of living with family)' },
      { ja: 'お気に入りの収納術や整理整頓のコツ', en: 'Your favorite storage technique or organizing tip' },
      { ja: '生活リズムは規則的？不規則？', en: 'Is your daily routine regular or irregular?' },
      { ja: 'お気に入りのスキンケアやヘアケア', en: 'Your favorite skincare or hair care routine' },
      { ja: '休日に絶対やらないこと', en: 'Something you absolutely never do on your day off' },
      { ja: '家の中で一番好きな家具やアイテム', en: 'Your favorite piece of furniture or item in your house' },
      { ja: '生活費を節約するために工夫していること', en: 'Something you do to save money in your daily life' },
      { ja: 'お気に入りの自炊メニューのルーティン', en: 'A go-to home-cooked meal routine you have' },
      { ja: 'ストレス解消のためにしていること', en: 'Something you do to relieve stress' },
      { ja: '週末の理想的な過ごし方', en: 'Your ideal way to spend the weekend' },
      { ja: 'お気に入りのカフェやお店での過ごし方', en: 'How you like to spend time at your favorite cafe or shop' },
      { ja: '生活の中で一番大切にしている時間', en: 'The time you value most in your daily life' },
      { ja: 'お気に入りの音楽プレイリストのジャンル', en: 'The genre of your favorite music playlist' },
      { ja: '生活の質を上げるためにやっていること', en: 'Something you do to improve your quality of life' },
      { ja: 'お気に入りのリラックスできる音やBGM', en: 'Your favorite relaxing sound or background music' },
      { ja: '生活の中で一番こだわっている香りのアイテム', en: 'The scented item you care about most in daily life' },
      { ja: '休日にやる「自分時間」の過ごし方', en: 'How you spend your personal “me time” on a day off' },
    ],
  },
  {
    id: 'deep',
    labelKey: 'topic.category.deep',
    icon: '🧠',
    topics: [
      { ja: '人生の中で一番影響を受けた本や言葉', en: 'The book or quote that has influenced your life the most' },
      { ja: '自分が「大人になったな」としみじみ感じた瞬間', en: 'The moment you truly felt like you have become an adult' },
      { ja: 'これまでの人生で「最大の挑戦」だったと思うこと', en: 'What you consider the biggest challenge of your life so far' },
      { ja: '自分の性格で「ここが好き」「ここは直したい」ところ', en: 'What you like and what you wish to change about your personality' },
      { ja: '初対面の人と話すときに、つい見ちゃうところや気にするポイント', en: 'What you notice first or care about when talking to someone for the first time' },
      { ja: '「これをされている時が一番幸せ！」と感じる瞬間', en: 'The exact moment you feel the happiest' },
      { ja: '10年後の自分はどうなっていると思う？（またはどうなっていたい？）', en: 'Where do you think you will be (or want to be) in 10 years?' },
      { ja: '落ち込んだとき、どうやって立ち直ることが多い？', en: 'How do you usually bounce back when you are feeling down?' },
      { ja: '人付き合い（人間関係）で一番大切にしていること', en: 'The most important thing to you when building relationships' },
      { ja: '「これがあるから人生楽しい！」と言い切れるものは何？', en: 'What is the one thing that makes life truly fun for you?' },
      { ja: '今までで一番嬉しかった褒め言葉', en: 'The compliment that made you happiest' },
      { ja: '自分にとっての「成功」の定義', en: 'Your personal definition of success' },
      { ja: '誰かに感謝を伝えたいと思っている出来事', en: 'Something you are grateful to someone for' },
      { ja: '今の自分を一言で表すとしたら？', en: 'If you had to describe yourself in one word, what would it be?' },
      { ja: '自分の価値観に一番影響を与えた経験', en: 'An experience that most influenced your values' },
      { ja: '誰かに本当に救われたと感じた瞬間', en: 'A moment you truly felt saved by someone' },
      { ja: '人生で一番後悔していること（または後悔していないこと）', en: 'Something you regret in life (or do not regret)' },
      { ja: '自分が一番大切にしている信念', en: 'A belief you value the most' },
      { ja: '人と意見が違うときどう向き合う？', en: 'How do you handle situations when you disagree with someone?' },
      { ja: '今までで一番勇気を出した経験', en: 'A time you mustered up the most courage' },
      { ja: '自分にとっての「強さ」とは何か', en: 'What does “strength” mean to you?' },
      { ja: 'これまでで一番大きな決断', en: 'The biggest decision you have made' },
      { ja: '自分が変わったと感じるきっかけ', en: 'Something that made you feel you have changed' },
      { ja: '人生で一番大切な人は誰？その理由', en: 'Who is the most important person in your life, and why?' },
      { ja: '自分にとっての「居場所」とはどこ？', en: 'Where do you consider your “place to belong”?' },
      { ja: '今の自分を作った経験ベスト3', en: 'Top 3 experiences that shaped who you are today' },
      { ja: '失敗から学んだ一番大きなこと', en: 'The biggest lesson you learned from a failure' },
      { ja: '人に優しくできた瞬間で一番印象的なもの', en: 'The most memorable moment you were kind to someone' },
      { ja: '自分の中で変わらない「軸」になっているもの', en: 'Something that has remained a constant core part of you' },
      { ja: 'これまでで一番心が動いた言葉', en: 'Words that moved you the most' },
      { ja: '自分が幸せを感じる条件', en: 'The conditions under which you feel happy' },
      { ja: '将来後悔しないために今やっておきたいこと', en: 'Something you want to do now so you will not regret it later' },
      { ja: '自分にとっての「成長」を感じた瞬間', en: 'A moment you felt you had grown' },
      { ja: '大切な人にまだ伝えていない感謝の気持ち', en: 'Gratitude you have not yet expressed to someone important' },
      { ja: '自分が一番自分らしくいられる瞬間', en: 'The moment you feel most like yourself' },
      { ja: 'これまでで一番自分を変えた出会い', en: 'The encounter that changed you the most' },
      { ja: '今の自分を肯定できるところ', en: 'A part of yourself you can fully accept and embrace' },
      { ja: '過去の自分に感謝したいこと', en: 'Something you want to thank your past self for' },
      { ja: '人生で一番怖かった経験', en: 'The scariest experience in your life' },
      { ja: '自分にとっての「逃げ道」になっているもの', en: 'Something that serves as your escape or comfort' },
      { ja: 'これからの人生で一番大切にしたいこと', en: 'Something you want to value most in the rest of your life' },
      { ja: '自分を支えてくれている考え方や言葉', en: 'A way of thinking or a phrase that supports you' },
      { ja: '人と深く繋がれたと感じた経験', en: 'An experience where you felt deeply connected with someone' },
      { ja: '今までで一番自分に正直になれた瞬間', en: 'A moment you were most honest with yourself' },
      { ja: '将来の自分へ伝えたい一言', en: 'A message you would like to leave for your future self' },
      { ja: '人生において一番大切にしているバランス', en: 'A balance you value most in your life' },
      { ja: '自分の中の弱さと、どう向き合っている？', en: 'How do you cope with your own weaknesses?' },
      { ja: '人生で一番心に残っている景色や瞬間', en: 'The scenery or moment that has stayed with you the most in life' },
      { ja: '自分が誰かに与えられた一番大きな影響', en: 'The biggest influence you have had on someone else' },
      { ja: '「自分らしさ」を一言で表すなら？', en: 'If you had to express “being yourself” in one phrase, what would it be?' },
    ],
  },
  {
    id: 'school',
    labelKey: 'topic.category.school',
    icon: '🏫',
    topics: [
      { ja: '学生時代に一番楽しかった思い出', en: 'Your favorite memory from school days' },
      { ja: '一番好きだった、または得意だった教科', en: 'The subject you liked or were best at' },
      { ja: '部活・サークルでの思い出', en: 'A memory from your club or extracurricular activities' },
      { ja: '学生時代に仲の良かった友達との思い出', en: 'A memory with close friends from school' },
      { ja: '修学旅行や校外学習で一番印象に残っていること', en: 'The most memorable part of a school trip or field trip' },
      { ja: '子供の頃に夢中になっていたこと', en: 'Something you were obsessed with as a kid' },
      { ja: '学生時代にやっておけばよかったと思うこと', en: 'Something you wish you had done during your school days' },
      { ja: '初恋の思い出', en: 'A memory of your first crush' },
      { ja: '一番好きだった先生の思い出', en: 'A memory of your favorite teacher' },
      { ja: '子供の頃のあだ名やニックネーム', en: 'A nickname you had as a kid' },
      { ja: '小学校・中学校・高校で一番好きだった時期', en: 'Which school years did you like the most: elementary, middle, or high school?' },
      { ja: '学生時代に流行っていたものでよく覚えていること', en: 'A trend from your school days that you remember well' },
      { ja: '学生時代の文化祭や体育祭の思い出', en: 'A memory from a school festival or sports day' },
      { ja: '学生時代に好きだった給食や学食のメニュー', en: 'Your favorite school lunch or cafeteria menu from your school days' },
      { ja: '学生時代のテストや勉強で苦労したこと', en: 'Something you struggled with during exams or studying in school' },
      { ja: 'クラスでの自分の立ち位置（キャラ）', en: 'Your role or position in your class' },
      { ja: '学生時代に流行っていた持ち物やグッズ', en: 'An item or accessory that was trendy during your school days' },
      { ja: '放課後によくしていたこと', en: 'Something you often did after school' },
      { ja: '学生時代の恥ずかしいエピソード', en: 'An embarrassing episode from your school days' },
      { ja: 'クラスメイトとのケンカや仲直りの思い出', en: 'A memory of a fight and making up with a classmate' },
      { ja: '学生時代に習っていた習い事', en: 'A lesson or extracurricular activity you took as a student' },
      { ja: '卒業式や入学式で印象に残っていること', en: 'Something memorable from a graduation or entrance ceremony' },
      { ja: '学生時代にあだ名で呼ばれていた？', en: 'Did you have a nickname during your school days?' },
      { ja: '夏休み・冬休みの思い出', en: 'A memory from summer or winter vacation as a student' },
      { ja: '学生時代に憧れていた先輩や同級生', en: 'A senior or classmate you admired during your school days' },
      { ja: '学生時代に一番大変だった行事', en: 'The most challenging school event you experienced' },
      { ja: '学生時代によく買い食いしていたもの', en: 'Snacks you often bought and ate after school' },
      { ja: '学生時代の部活・サークルでの役職や役割', en: 'Your position or role in a club or extracurricular activity' },
      { ja: '学生時代に一番真剣に取り組んだこと', en: 'Something you worked on most seriously during your school days' },
      { ja: 'クラス替えで仲良くなったきっかけ', en: 'How you became friends after a class reshuffle' },
      { ja: '学生時代の恋愛事情', en: 'Your love life during your school days' },
      { ja: '学生時代にやっていたアルバイトの思い出', en: 'A memory from a part-time job during your school days' },
      { ja: '学校の宿題で一番苦労した思い出', en: 'A memory of struggling with homework' },
      { ja: '学生時代に流行っていた遊び', en: 'A game that was popular during your school days' },
      { ja: '卒業文集や卒業アルバムに書いたこと', en: 'Something you wrote in your graduation memory book or yearbook' },
      { ja: '学生時代に一番仲が良かった友達との今の関係', en: 'Your current relationship with your closest friend from school' },
      { ja: '学生時代の制服や私服のこだわり', en: 'Your preferences about your school uniform or casual clothes during school' },
      { ja: '学生時代にやっておけば良かった後悔', en: 'Something you regret not doing during your school days' },
      { ja: '学生時代の自由研究や課題で印象的だったもの', en: 'A memorable independent research project or assignment from your school days' },
      { ja: '学生時代のクラブ活動の大会や発表会の思い出', en: 'A memory from a club competition or presentation during your school days' },
      { ja: '学生時代にハマっていたお菓子や飲み物', en: 'Snacks or drinks you were obsessed with during school days' },
      { ja: '学生時代に好きだった休み時間の過ごし方', en: 'How you liked to spend recess during your school days' },
      { ja: '席替えで一番嬉しかった席', en: 'The seat you were happiest to get during a seat change' },
      { ja: '学生時代の自由な服装や髪型のルール', en: 'Rules about clothing or hairstyles during your school days' },
      { ja: '学生時代の宿題を最後までやらずに焦った経験', en: 'An experience of rushing because you had not finished homework' },
      { ja: 'クラスや学校全体で盛り上がった出来事', en: 'An event that got the whole class or school excited' },
      { ja: '学生時代の先生にされて嬉しかったこと', en: 'Something a teacher did that made you happy during your school days' },
      { ja: '学生時代に流行っていた話し方や言葉', en: 'A way of speaking or slang that was trendy during your school days' },
      { ja: '体育の授業で得意・不得意だったこと', en: 'Something you were good or bad at in P.E. class' },
      { ja: '学生時代の保健室や図書室の思い出', en: 'A memory of the school infirmary or library' },
    ],
  },
  {
    id: 'tech',
    labelKey: 'topic.category.tech',
    icon: '💻',
    topics: [
      { ja: '今一番欲しいガジェット', en: 'The gadget you want the most right now' },
      { ja: '使っていてよかったと思うアプリやサービス', en: 'An app or service you are glad you started using' },
      { ja: 'もしAIに何でも1つだけ頼めるなら何を頼む？', en: 'If you could ask an AI to do one thing for you, what would it be?' },
      { ja: 'スマホの中で一番使用時間が長いアプリ', en: 'The app you spend the most time on, on your phone' },
      { ja: '便利だけどあまり知られていないと思う機能やサービス', en: 'A useful but underrated feature or service' },
      { ja: '昔使っていたけど今は使っていないSNSやサービス', en: 'An SNS or service you used to use but no longer do' },
      { ja: 'パソコンとスマホ、作業するならどっちが好き？', en: 'Do you prefer working on a PC or a smartphone?' },
      { ja: '一番好きなSNSとその理由', en: 'Your favorite SNS and why' },
      { ja: '近い将来実現してほしいテクノロジー', en: 'A technology you hope will become a reality in the near future' },
      { ja: 'スマホは何年くらいで買い替える？', en: 'How often do you replace your smartphone?' },
      { ja: '一番使いこなしていると思うガジェット', en: 'The gadget you feel you have mastered the most' },
      { ja: 'スマホの中で一番容量を使っているもの', en: 'What takes up the most storage on your phone?' },
      { ja: 'AIにやってもらいたい家事や作業', en: 'A household chore or task you would like an AI to do for you' },
      { ja: '好きなガジェットブランド', en: 'Your favorite gadget brand' },
      { ja: 'パソコンのデスクトップやホーム画面のこだわり', en: 'Your preferences for your computer desktop or home screen layout' },
      { ja: '一番便利だと思うスマホの機能', en: 'The smartphone feature you find most useful' },
      { ja: '昔欲しかったけど買えなかったガジェット', en: 'A gadget you wanted in the past but could not buy' },
      { ja: 'スマホ・PC以外で持っているデジタル機器', en: 'Digital devices you own besides a smartphone or PC' },
      { ja: 'ゲーム機で一番思い入れのあるもの', en: 'The game console you have the most attachment to' },
      { ja: 'イヤホン・ヘッドホンのこだわり', en: 'Your preferences for earphones or headphones' },
      { ja: 'SNSで一番よく使う機能', en: 'The feature you use most often on SNS' },
      { ja: 'スマホの通知設定はどうしている？', en: 'How do you manage your smartphone notification settings?' },
      { ja: '最近知って驚いたテクノロジーの進化', en: 'A technological advancement that recently surprised you' },
      { ja: '一番お気に入りのアプリのアイコンやデザイン', en: 'Your favorite app icon or design' },
      { ja: 'スマートホーム機器を使っている、または使いたい？', en: 'Do you use or want to use smart home devices?' },
      { ja: '写真や動画はどこに保存している？', en: 'Where do you store your photos and videos?' },
      { ja: '一番使っているクラウドサービス', en: 'The cloud service you use the most' },
      { ja: 'タイピングは早い？よく使うショートカットキー', en: 'Are you a fast typist? What shortcut keys do you use often?' },
      { ja: 'VRやARに興味はある？', en: 'Are you interested in VR or AR?' },
      { ja: 'スマホゲームでよくやるジャンル', en: 'The genre of mobile games you often play' },
      { ja: 'デジタルデトックスをしたことはある？', en: 'Have you ever done a digital detox?' },
      { ja: '一番使っている検索エンジンやAIツール', en: 'The search engine or AI tool you use the most' },
      { ja: 'お気に入りのキーボードやマウス', en: 'Your favorite keyboard or mouse' },
      { ja: 'スマホの待ち受け画面のこだわり', en: 'Your preferences for your smartphone wallpaper' },
      { ja: 'これから欲しいと思っているガジェット', en: 'A gadget you want to get in the future' },
      { ja: 'パソコンは自作派？既製品派？', en: 'Do you prefer building your own PC or buying a pre-built one?' },
      { ja: 'デジタル機器の整理整頓やケーブル収納のコツ', en: 'Your tips for organizing digital devices or cables' },
      { ja: '音声アシスタント（Siri、Alexaなど）は使っている？', en: 'Do you use voice assistants like Siri or Alexa?' },
      { ja: '未来に実現してほしいガジェットのアイデア', en: 'An idea for a gadget you hope will exist in the future' },
      { ja: '毎日必ず確認するアプリ', en: 'An app you check every single day' },
      { ja: 'ガジェットを選ぶときに一番重視するポイント', en: 'The point you value most when choosing a gadget' },
      { ja: 'デジタル機器の充電が切れて困った経験', en: 'An experience where you were in trouble because your device ran out of battery' },
      { ja: 'スマホの画面を割ったり壊した経験', en: 'An experience of cracking or breaking your phone screen' },
      { ja: '一番使いやすいと思うメッセージアプリ', en: 'The messaging app you find easiest to use' },
    ],
  },
  {
    id: 'season',
    labelKey: 'topic.category.season',
    icon: '🎐',
    topics: [
      { ja: '夏といえば思い出すこと', en: 'Something that reminds you of summer' },
      { ja: '冬の楽しみ方', en: 'How you enjoy winter' },
      { ja: '今年やりたい季節の予定（花見・花火・紅葉狩りなど）', en: 'A seasonal plan you want to do this year (flower viewing, fireworks, fall leaves, etc.)' },
      { ja: '誕生日の思い出やプレゼントで嬉しかったもの', en: 'A birthday memory or a gift that made you happy' },
      { ja: '好きな年中行事・イベント', en: 'Your favorite annual event or holiday' },
      { ja: '今年やった、またはやりたい年末年始の過ごし方', en: 'How you spent or want to spend the New Year holidays' },
      { ja: 'クリスマスや年末の過ごし方', en: 'How you spend Christmas or the end of the year' },
      { ja: '梅雨・台風など天気が悪い日の過ごし方', en: 'How you spend rainy or stormy days' },
      { ja: '春といえば思い出すこと', en: 'Something that reminds you of spring' },
      { ja: '秋の楽しみ方', en: 'How you enjoy autumn' },
      { ja: 'お正月の過ごし方', en: 'How you spend the New Year holidays' },
      { ja: '夏休み・冬休みでやりたいこと', en: 'Something you want to do during summer or winter break' },
      { ja: '花火大会の思い出', en: 'A memory from a fireworks festival' },
      { ja: 'お花見の思い出', en: 'A memory from cherry blossom viewing' },
      { ja: 'バレンタインやホワイトデーの思い出', en: "A memory from Valentine's Day or White Day" },
      { ja: 'ハロウィンの楽しみ方', en: 'How you enjoy Halloween' },
      { ja: '夏祭りで好きな屋台の食べ物', en: 'Your favorite food stall item at a summer festival' },
      { ja: '梅雨の時期の過ごし方', en: 'How you spend the rainy season' },
      { ja: '雪が降ったらやりたいこと', en: 'Something you want to do when it snows' },
      { ja: '年末の大掃除はしっかりやる派？', en: 'Do you do a thorough year-end cleaning?' },
      { ja: 'GWや連休の過ごし方', en: 'How you spend Golden Week or long holidays' },
      { ja: '七夕の願い事', en: 'Your wish for Tanabata (Star Festival)' },
      { ja: '卒業や入学のシーズンの思い出', en: 'A memory from the graduation or entrance season' },
      { ja: '夏のレジャーで好きなこと', en: 'Your favorite summer leisure activity' },
      { ja: '冬に必ず食べたくなるもの', en: 'Something you always crave in winter' },
      { ja: 'クリスマスプレゼントで嬉しかったもの', en: 'A Christmas present that made you happy' },
      { ja: '年越しはどうやって過ごす？', en: "How do you spend New Year's Eve?" },
      { ja: '季節のイベントで一番好きなもの', en: 'Your favorite seasonal event' },
      { ja: '衣替えのタイミングや基準', en: 'Your timing and rules for switching out your seasonal wardrobe' },
      { ja: '夏の暑さ対策でやっていること', en: 'Something you do to deal with summer heat' },
      { ja: '冬の寒さ対策でやっていること', en: 'Something you do to deal with winter cold' },
      { ja: '季節ごとに変える生活習慣', en: 'A lifestyle habit you change depending on the season' },
      { ja: '祝日で一番好きな日', en: 'Your favorite public holiday' },
      { ja: '季節限定のお菓子やドリンクで好きなもの', en: 'Your favorite seasonal limited snack or drink' },
      { ja: 'その季節になると必ず聴きたくなる曲', en: 'A song you always want to listen to when that season arrives' },
      { ja: '夏フェスやライブイベントの思い出', en: 'A memory from a summer festival or live event' },
      { ja: '新年の抱負を立てる派？', en: "Do you set New Year's resolutions?" },
      { ja: '敬老の日や母の日・父の日の思い出', en: "A memory from Respect for the Aged Day, Mother's Day, or Father's Day" },
      { ja: '夏休みの自由研究や宿題の思い出', en: 'A memory about summer vacation projects or homework' },
      { ja: 'お月見や十五夜の思い出', en: 'A memory of moon viewing or the mid-autumn festival' },
      { ja: '節分や豆まきの思い出', en: 'A memory of Setsubun or bean-throwing' },
      { ja: 'こどもの日や雛祭りの思い出', en: "A memory of Children's Day or Girls' Day" },
      { ja: '年賀状や年始の挨拶の思い出', en: "A memory of New Year's cards or greetings" },
      { ja: '大晦日にやる恒例行事', en: "An annual tradition you do on New Year's Eve" },
      { ja: '季節の変わり目に必ずやること', en: 'Something you always do at the change of seasons' },
      { ja: '夏休みの思い出', en: 'A memory of your summer vacation' },
    ],
  },
  {
    id: 'romance',
    labelKey: 'topic.category.romance',
    icon: '💕',
    topics: [
      { ja: '好きなタイプ', en: 'Ideal type' },
      { ja: 'デートで行きたい場所', en: 'A place you would like to go on a date' },
      { ja: '恋人との理想のライフスタイル', en: 'Your ideal lifestyle with a partner' },
      { ja: '別れた相手と友達に戻れる派？', en: 'Do you believe it is possible to remain friends after a breakup?' },
      { ja: '価値観のズレを感じたとき、どう向き合う？', en: 'How do you handle differences in values when they arise in a relationship?' },
      { ja: '「大切にされていない」と感じてしまう瞬間', en: 'The moments when you feel you are not being treated well' },
      { ja: '失恋から立ち直るための自分なりの方法', en: 'How you personally recover from a heartbreak' },
      { ja: '恋人に対して気持ちが冷めてしまう瞬間', en: 'The moment you feel your feelings for your partner fading' },
      { ja: '恋人に求める一番大切な条件', en: 'The most important quality you look for in a partner' },
      { ja: '恋愛で一番大切にしていること', en: 'Something you value most in a relationship' },
      { ja: 'これまでで一番印象的だった告白', en: 'The most memorable confession you experienced' },
      { ja: '思わずキュンとする異性の仕草や行動', en: 'A gesture or behavior from someone that makes your heart flutter' },
      { ja: '人を好きになるきっかけ', en: 'What makes you start liking someone' },
      { ja: '恋愛で一番ドキドキした瞬間', en: 'The most heart-fluttering moment in a relationship' },
      { ja: '理想のデートプラン', en: 'Your ideal date plan' },
      { ja: '恋人とのケンカで多い原因', en: 'A common cause of arguments with a partner' },
      { ja: '相手のどんな行動に「好き」を感じる？', en: 'What kind of behavior makes you feel someone likes you?' },
      { ja: '遠距離恋愛をしたことはある？', en: 'Have you ever been in a long-distance relationship?' },
      { ja: '恋愛で後悔していること', en: 'Something you regret about a past relationship' },
      { ja: '恋人にしてもらって一番嬉しかったこと', en: 'Something a partner did for you that made you the happiest' },
      { ja: 'プロポーズされたい・したいシチュエーション', en: 'Your ideal marriage proposal scenario (whether proposing or being proposed to)' },
      { ja: '過去の恋愛で学んだこと', en: 'Something you learned from a past relationship' },
      { ja: '恋愛における「運命」を信じる？', en: 'Do you believe in “fate” when it comes to love?' },
      { ja: '初デートで緊張したエピソード', en: 'An episode where you were nervous on a first date' },
      { ja: '理想の休日のデートプラン', en: 'Your ideal weekend date plan' },
      { ja: '好きな人へのアプローチ方法', en: 'Your approach when trying to get closer to someone you like' },
      { ja: '恋人と信頼関係を築くために大切だと思うこと', en: 'What do you think is important for building trust in a relationship?' },
      { ja: '恋愛と趣味、どちらを優先したい？', en: 'Would you prioritize your relationship or your hobbies?' },
      { ja: '理想の「愛し方・愛され方」とは？', en: 'What is your ideal way of loving and being loved?' },
      { ja: '結婚に対するイメージや理想', en: 'Your image or ideal of marriage' },
      { ja: 'あなたが思う恋愛で一番大事なものは？', en: 'What do you think is the most important thing in a relationship?' },
      { ja: '恋愛においての理想の年齢差', en: 'Your ideal age difference in a relationship' },
      { ja: '恋人とは毎日連絡を取りたい派？', en: 'Do you prefer to keep in touch with your partner every day?' },
      { ja: '恋人に内緒にしていることはある？', en: 'Do you keep any secrets from a partner?' },
      { ja: '恋愛にときめきは必要？それとも安心感重視？', en: 'In a relationship, do you prioritize excitement or a sense of security?' },
      { ja: '学生時代の恋愛事情', en: 'Your love life during your school days' },
      { ja: '初恋の思い出', en: 'A memory of your first crush' },
      { ja: '恋人の過去の恋愛は気になる？', en: 'Do you care about your partner\'s past relationships?' },
      { ja: '恋人に作ってほしい料理', en: 'A dish you want your partner to cook for you' },
      { ja: '恋人と一緒に始めたい趣味', en: 'A hobby you want to start with your partner' },
      { ja: '恋愛映画と恋愛小説、どちらが好き？', en: 'Do you prefer romantic movies or romantic novels?' },
      { ja: '恋人の前で泣いたことはある？', en: 'Have you ever cried in front of your partner?' },
      { ja: 'デートの支払いはどうしたい？', en: 'How do you prefer to handle paying on dates?' },
      { ja: '恋人の家族に会うのは緊張する？', en: 'Are you nervous about meeting your partner\'s family?' },
      { ja: '一目惚れをしたことはある？', en: 'Have you ever fallen in love at first sight?' },
      { ja: '復縁についてどう思う？', en: 'What are your thoughts on getting back together with an ex?' },
      { ja: '恋人から言われて一番嬉しかった言葉', en: 'The most pleasing words you have heard from a partner' },
      { ja: '理想の告白のセリフ', en: 'Your ideal confession line' },
      { ja: 'ペアルックについてどう思う？', en: 'What do you think about wearing matching outfits?' },
      { ja: '恋人と旅行に行くならどこ？', en: 'Where would you go on a trip with your partner?' },
      { ja: '嫉妬深い方だと思う？', en: 'Do you consider yourself the jealous type?' },
      { ja: '恋愛で一番成長したと感じること', en: 'Something you feel you have grown the most in through romance' },
      { ja: '恋人に甘えたい派？甘えられたい派？', en: 'Do you prefer to be pampered or to pamper your partner?' },
      { ja: '好きな人には自分からアピールする？', en: 'Do you proactively approach someone you like?' },
      { ja: '恋人との最高の休日の過ごし方', en: 'The best way to spend a day off with your partner' },
      { ja: '恋愛において絶対に許せないこと', en: 'Something you absolutely cannot forgive in a relationship' }
    ],
  },
  {
    id: 'relationship',
    labelKey: 'topic.category.relationship',
    icon: '🤝',
    topics: [
      { ja: '初対面の人と距離を縮めるのは得意？', en: 'Are you good at getting close to people you just met?' },
      { ja: '友達に直してほしいと思ったこと', en: 'Something you wished a friend would change' },
      { ja: '友達と遊ぶとき、計画を立てる派？行き当たりばったり派？', en: 'Do you plan out hangouts with friends or just wing it?' },
      { ja: '友達の誕生日はしっかり祝う派？', en: 'Do you like to properly celebrate your friends\' birthdays?' },
      { ja: '人を信頼できるようになるまでの基準', en: 'What it takes for you to start trusting someone' },
      { ja: '友達の人数は多い？少数派？', en: 'Do you prefer having many friends or just a few close ones?' },
      { ja: '友達との連絡の頻度はどれくらいが理想？', en: 'What is your ideal frequency for keeping in touch with friends?' },
      { ja: '相手の長所を伝えるのは得意？', en: 'Are you good at telling people their strengths?' },
      { ja: '友達とケンカした時の仲直りの仕方', en: 'How you make up after a fight with a friend' },
      { ja: '人間関係で一番気をつけていること', en: 'Something you are careful about in relationships with others' },
      { ja: '「親友」だと思える友達の条件', en: 'What makes you consider a friend a "best friend"?' },
      { ja: '友達へプレゼントを選ぶときに大事にすること', en: 'Something you care about when choosing a gift for a friend' },
      { ja: '友達の些細な変化に気づける？', en: 'Are you good at noticing small changes in your friends?' },
      { ja: '友達を作るのが得意？それとも苦手？', en: 'Are you good at making friends, or not so much?' },
      { ja: '友達と喧嘩した後の連絡のタイミング', en: 'When you usually reach out after a fight with a friend' },
      { ja: '人を褒めるのは得意？', en: 'Are you good at complimenting people?' },
      { ja: '人付き合いで疲れたときの対処法', en: 'How you cope when you are tired from socializing' },
      { ja: '友達に一番感謝していること', en: 'Something you are most thankful to a friend for' },
      { ja: '最近会えて嬉しかった人', en: 'Someone you were happy to see recently' },
      { ja: '最近、誰かに感謝したこと', en: 'Something you were thankful to someone for recently' },
      { ja: '今年新しく出会った人との思い出', en: 'A memory with someone you met this year' },
      { ja: '初対面の人と話すときに、つい見ちゃうところや気にするポイント', en: 'What you notice first or care about when talking to someone for the first time' },
      { ja: '人付き合い（人間関係）で一番大切にしていること', en: 'The most important thing to you when building relationships' },
      { ja: '感謝を伝えたいと思っている出来事', en: 'Something you are grateful for' },
      { ja: '本当に救われたと感じた瞬間', en: 'A moment you truly felt saved' },
      { ja: '人と意見が違うときどう向き合う？', en: 'How do you handle situations when you disagree with someone?' },
      { ja: '人に優しくできた瞬間で一番印象的なもの', en: 'The most memorable moment you were kind to someone' },
      { ja: 'お世話になった人にまだ伝えていない感謝の気持ち', en: 'Gratitude you have not yet expressed to someone who helped you' },
      { ja: 'これまでで一番自分を変えた友人や恩師との出会い', en: 'The encounter with a friend or mentor that changed you the most' },
      { ja: '人と深く繋がれたと感じた経験', en: 'An experience where you felt deeply connected with someone' },
      { ja: '自分が誰かに与えられた一番大きな影響', en: 'The biggest influence you have had on someone else' },
      { ja: '学生時代に仲の良かった友達との思い出', en: 'A memory with close friends from school' },
      { ja: 'クラスメイトとのケンカや仲直りの思い出', en: 'A memory of a fight and making up with a classmate' },
      { ja: 'クラス替えで仲良くなったきっかけ', en: 'How you became friends after a class reshuffle' },
      { ja: '学生時代に一番仲が良かった友達との今の関係', en: 'Your current relationship with your closest friend from school' },
      { ja: '仕事仲間との理想的な関係', en: 'Your ideal relationship with coworkers' },
      { ja: '将来一緒に働きたいと思うタイプの人', en: 'The type of person you would like to work with in the future' },
      { ja: '仕事・勉強で一番感謝した人', en: 'Someone you were most thankful to at work or study' },
      { ja: '一緒に趣味を楽しめる友達はいる？', en: 'Do you have friends who share your hobby?' },
      { ja: '趣味を通じて得た友達やつながり', en: 'Friends or connections you made through your hobby' },
      { ja: '苦手なタイプの人とどう接する？', en: 'How do you interact with people you do not get along with?' },
      { ja: '年上の人と年下の人、どちらが話しやすい？', en: 'Is it easier for you to talk to older or younger people?' },
      { ja: '友達の秘密を知ってしまったらどうする？', en: 'What would you do if you found out a friend\'s secret?' },
      { ja: '人間関係で一番ストレスを感じる瞬間', en: 'The moment you feel the most stress in relationships' },
      { ja: '悩み事を相談されるのは得意？', en: 'Are you good at giving advice when someone confides in you?' },
      { ja: '最近の自分を象徴する一言', en: 'A word that describes you lately' },
      { ja: '友達に言われて一番嬉しかった言葉', en: 'The happiest thing a friend has ever said to you' },
      { ja: '自分の弱みを人に見せることはできる？', en: 'Are you able to show your weaknesses to others?' },
      { ja: '誰かと一緒にいるとき沈黙は気まずい？', en: 'Do you find silence awkward when you are with someone?' },
      { ja: 'グループでの会話と1対1の会話、どちらが好き？', en: 'Do you prefer group conversations or one-on-one conversations?' }
    ],
  },
];